Changes to chat
lucasmonstro/PyTibia pull request #30
Opened 2022-10-12 20:35 UTC by augustocrmattos

-Check position por all three main tabs (loot, local and NPC) -Created method to check if a tab is selected
-Added cache to tabs positions
-Changed tabs structure to Dict so it is easier to add more tabs

2022-10-14 09:38 UTC, lucasmonstro requested changes

2022-10-14 09:38 UTC, lucasmonstro commented on chat/chat.py
>      chatMenu = getChatMenuPos(screenshot)
```suggestion
    chatMenuPos = getChatMenuPos(screenshot)
```

2022-10-14 09:38 UTC, lucasmonstro commented on chat/chat.py
>      return leftSidebarArrows[0] + 10, chatMenu[1], chatMenu[0] - (leftSidebarArrows[0] + 10), 20
Pode colocar isso numa variavel?

2022-10-14 09:38 UTC, lucasmonstro commented on chat/chat.py
>  def getChatsTabs(screenshot):
Seria algo como getChatsTabsContainer? Você está pegando a posição dos containers das tabs?

2022-10-14 09:38 UTC, lucasmonstro commented on chat/chat.py
> +@utils.core.cacheObjectPos
Uma vez que o conteúdo muda a todo momento, esse decorator não vai ter efeito. Ele é apenas útil para conteúdo estático

2022-10-14 09:38 UTC, lucasmonstro commented on chat/chat.py
> +@utils.core.cacheObjectPos
Uma vez que o conteúdo muda a todo momento, esse decorator não vai ter efeito. Ele é apenas útil para conteúdo estático

2022-10-14 09:38 UTC, lucasmonstro commented on chat/chat.py
>      chatStatus = getChatStatus(screenshot)
```suggestion
    chatMenuPos = getChatMenuPos(screenshot)
    chatStatusPos = getChatStatusPos(screenshot)
```

2022-10-14 09:38 UTC, lucasmonstro commented on chat/chat.py
>      return leftSidebarArrows[0], chatMenu[1] + 18, chatStatus[0][0] + 40, (chatStatus[0][1] - 6) - (chatMenu[1] + 13)
Pode colocar isso numa variável explicativa?

2022-10-20 18:51 UTC, augustocrmattos commented on chat/chat.py
> +@utils.core.cacheObjectPos
Ele é estático, a posição das tabs não vai mudar, nem se deslocar.

2022-10-20 18:51 UTC, augustocrmattos commented on chat/chat.py
> +@utils.core.cacheObjectPos
Esse container não muda de posição

2022-10-20 18:57 UTC, augustocrmattos commented on chat/chat.py
>      chatMenu = getChatMenuPos(screenshot)
mudado

2022-10-20 18:58 UTC, augustocrmattos commented on chat/chat.py
> +chatTabs = [
Já está em um dict, eu crio e converto pra um dict logo abaixo.

2022-10-22 02:34 UTC, lucasmonstro approved these changes

2022-10-22 02:34 UTC, merged