👷 portuguese language README
lucasmonstro/PyTibia pull request #43
Opened 2022-12-06 18:04 UTC by evitarafadiga

README translation, modifications and author added (me).

2022-12-06 22:09 UTC, lucasmonstro requested changes

2022-12-07 20:07 UTC, evitarafadiga commented on README.md
> +Copyright © 2023 [**lucasmonstro**](https://github.com/lucasmonstro)
copyright necessita data segundo a [iniciativa opensource](https://opensource.org/licenses/MIT)

2022-12-07 20:08 UTC, evitarafadiga commented on README.pt-BR.md
> +- [Licença](#licença)
removido

2022-12-08 13:19 UTC, evitarafadiga reviewed
correções

2023-02-15 02:39 UTC, closed without merging