README.es.md
lucasmonstro/PyTibia pull request #56
Opened 2023-04-22 17:43 UTC by Yaten

The Spanish readme file has been created as indicated in the pending tasks of the project.

Se ha creado el archivo readme en español según lo indicado en las tareas pendientes del proyecto

2023-04-22 23:15 UTC, lucasmonstro requested changes

2023-04-22 23:15 UTC, lucasmonstro commented on README.es.md
> +
Remove essas duas linhas.

2023-04-22 23:15 UTC, lucasmonstro commented on README.es.md
> +| Entrenar                  | :x:                |
Deixa isso bem formatado.

2023-04-22 23:17 UTC, lucasmonstro commented
@Yaten I will gonna ask for some spanish friend to check translate, is it ok for you?

2023-04-22 23:23 UTC, lucasmonstro commented
@Yaten you need to remove TODOs lines from README.md and README.pt-BR files:

https://github.com/lucasmonstro/PyTibia/blob/main/README.md?plain=1#L95
https://github.com/lucasmonstro/PyTibia/blob/main/README.pt-BR.md?plain=1#L95

2023-04-22 23:23 UTC, lucasmonstro commented
@Yaten Im using gitmoji to make commits, please, follow the same way and please, use english in commits. Thanks <3

2023-05-04 02:42 UTC, fmmendes commented
> @Yaten I will gonna ask for some spanish friend to check translate, is it ok for you?

I can send to some people to review too, because there are several types of Spanish (Spain, Latin America, Argentina, Catalán, etc.)

2023-05-16 23:43 UTC, closed without merging